global:
  scrape_interval: 5s   # 데이터 수집 최소 간격

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:     # worker node에 대한 정적 ip 할당
      - targets:
          - '211.183.3.201:9100'
          - '211.183.3.202:9100'
          - '211.183.3.203:9100'
          - '211.183.3.204:9100'
    
    # dns_sd_configs:     # worker node에 대해 자동으로 ip 할당
    #   - names:
    #       - 'tasks.node-exporter'
    #     type: 'A'
    #     port: 9100
